####
# 开发环境配置
####

  server:
    port: 8030
#    服务器本地路径
    fileSavePath: E:/log/
#    fileSavePath: C:/Program Files/Apache Software Foundation/Tomcat 8.5/webapps/ROOT
#    文件服务路径
    servUrl: http://192.168.3.112:8030

#服务注册
  eureka:
    client:
      service-url:
        defaultZone: http://192.168.3.112:8090/eureka
    #        defaultZone: http://zhuce.fangshangqu.cn/eureka
    instance:
      #      lease-renewal-interval-in-seconds: 10
      #      lease-expiration-duration-in-seconds: 5

      #    注册到eureka服务器的地址及端口,注意部署到tomcat后的端口问题
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}
      prefer-ip-address: true



 #本服务基本配置
  spring:
    application:
      name: BCB-PAY-SERVER

    #数据库
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/bcb-pay?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
      username: root
      password: root
      #添加阿里连接池
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        # 初始连接数
        initial-size: 5
        # 最大激活数
        max-active: 10

        minIdle: 3
        # 最大等待时间
        max-wait: 6000
        #超过时间限制是否回收
        removeAbandoned: true
        #超时时间；单位为秒。180秒=3分钟
        removeAbandonedTimeout: 180
        #是否记录当前线程的堆栈信息到日志中
        logAbandoned: true
        # Destroy线程会检测连接的间隔时间 || testWhileIdle的判断依据
        time-between-eviction-runs-millis: 60000

        minEvictableIdleTimeMillis: 300000

        # 验证的sql语句
        validation-query: select 1 from user
        # 验证超时
        validation-query-timeout: 3000

        # 连接时是否开启验证
        test-on-borrow: true
        # 退还连接时是否开启验证
        test-on-return: false
        # 建议配置为true，不影响性能，并且保证安全性
        test-while-idle: true

        # 是否启用非公平锁
        use-unfair-lock: true
        # mysql 用 false | oracle 用 true
        pool-prepared-statements: false
        # 启动监听、日志、防注入的功能
        filters: stat,log4j,wall

#配置redis
    redis:
      database: 0
      # Redis服务器地址
      host: 127.0.0.1
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      password: g5ymm5
      # 连接池最大连接数（使用负值表示没有限制）
#      pool:
#        max-active: 8
#      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1
#      # 连接池中的最大空闲连接
#        max-idle: 8
#      # 连接池中的最小空闲连接
#        min-idle: 0
#      # 连接超时时间（毫秒）
      timeout: 5000


    #配置jpa
    jpa:
      database: mysql
      show-sql: true
#      ddl-auto: create-drop
      hibernate:
        ddl-auto: update
#        ddl-auto: create

    http:
      encoding:
        force: true

    servlet:
      multipart:
        max-request-size: 10MB
        max-file-size: 10MB

    mvc:
      view:
        prefix: /
        suffix: .html

  pay:
    wx:
      mchId: 1513549201
      key: Bcb19e0814494a248d28c591d4bc31e1
      appId: wxa574b9142c67f42e
      autoReport: true
      useSandbox: false
      sandboxKey: 5ffeda033fb8fab92ae24d321257b01f
#      本地测试需每日更换
      notifyUrl: http://n925wj.natappfree.cc/pay/wx/notify
      certSn: 5663476TEREGD45FH63GDFHFG657FCHBFG
      certRootPath: D:/workspace/bcb-pay/src/main/webapp
      appSecret: D:/workspace/bcb-pay/src/main/webapp

    alipay:
      alipay-public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1EHvr+EMX5SM3NY9GtJrUNWGd6jeyeov6481Fi5ZFSxkuiY9MD8cYF1NZ/HrXZuXcrsFUTReZjm+Arl57tuU+It6dJga0R44yPirYJnJxxliAhjtY+pluQRUMaKwMMxap8i0aStdBj58frLWG3sr6QQD2V/DglQ6YaeFGMHLq9EMtQ87Hvms8P41t9x3PXBpsWQ44EYH6NI4eNgpgw47M6LQXNqG/5O0iE6E9iHvzMDE62M7Jm8fJULOMm9FEl8652jkquwB5W0291A84sXAhArkNCbckzbIRvMAw8Oohezkwis+l6uvQKqsUmagOD9flaM1IyK/oH6yhk2/2OprHwIDAQAB"
      app-private-key: "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCis0IiwL0UcEopVJXq1wAFXnINa/83UGZ8NiqOGzCZehPKQn1QsBTMIE5rUazPAVWZ95dNZV2s36rXXOT79JmaKRvQC/H4aDpj+lFnDNmqaRiCI/6iz8QvrEig5x4rYD40096uCS472L3LSkukaEGrTdGu6zHD8zpT7zr6Bvhf3PRaySSgnbMBsnkzge61tKMVV+D6E3zcL8tHlte/HXG3PcTLKj7yiyFVogAmgLI4P7qHns6SUWnIpN/KFjdY2qUwKJsvyUuTJ5VRWoOR8o7V4wSlTlRIfAaaDjtShYfIgNaxH6fkMG0tVdzknv5MhZG6a2plxeXpTA+j3wQA1YM9AgMBAAECggEAYQlGxZFsc/cw1AulykVmts0IeubRdX0XUre/k7e1uaOsj/It6WTLUp9mBe3VgjTKiCS58agmQYe4ze+Sho7w2ZfxBZlKPJx1TtGpoStx2ogJ3Px4z0PZP5GiU4zkWnxxPXKrmeLR11HCiK+MA8dGe1PTXl7Z9INpY0wIQbzMf+dCFSICYP/wiDUBp3NT287Bd9CJXFULogFVa2pqef6ZaWSiJmWGJC83speGWkuVzPBGqhoccGIdhK6ZInXTlxZbeHifH8esxJaXOpq11YIER5OhFRyFVavusZhLUojUawN2fDbqNJ1F6r8rDGeb6HMw5GyZkQYe/tLK7O1PvdsPwQKBgQDy6ByYoshN9ezYaZYmc+U9RgTS71h1P3VhxH0NE9dnCa14re5Gb5Zy67vljZ6aGaGkj0cvCAVTWhYLwUDZc3Os7KtgAc5/YPwtDiZrqh7tRt1xiIzmS84XGkj5IAKFVaLgaq9QUrb5t+BWfjmZjpFJMiB+DGYcbkoOACJKfCXusQKBgQCreF8YgsXogaVugwk2sZfFY7CnCfYtrXMBvlyT2ojD6Sg98ov7fKcffD/CoCdNVK7eQ6FSM1ldNP5hYqCT2fQ9GZQQus7kjvDWG/xLnnJ4hAM+yhB1na1juRJ26/4Mc2emEnql8UwB1ODJkVzsSIp0UydGP/ovRDqxo67p+hY4TQKBgQC99Am4y0N8w95NdnR26ZbRDdpj4cv5FIEEzZVFDskZyJWhk9KLvmOWxwYPA2qN85FWkL0H6GvRvNcUpjHCWuiQyBtUXtVPA1bxHOmqtESvJQWy7SfSSGGH64Q5XXDbOBbBDGzAkY6JRePnf5onnTe8V7jVGXkYrp62yCAIw4EeYQKBgHZw9hcDNdtNukzkvHeIIpLZMoufSOnyVm+M43vJxxC0O/TWVjUHvJT2CUDRyXQUG5ox0vvptj+4vEHek5atRZTy1yDbONANoHP07sf5EY8HeQplHwtvN/abPxLgHiLRkHXZa9i2HU9ikUcKXspjrSd+zLEsvg7qLTTJIKhD9Bc9AoGAEXCJfRc0sybza8kLkR8sw7lJvXCPHUEOxQwi9O2aSfvTxJZg2Y9vT/ernN74pXsaTgfqRM841FN2f0i+UwwerBU/pbsMzIh4WsyAttvQ3KHjUwVeuPZu22bOT5n+m1OsU0FG1STaymo5sjYRNa7t8FUVpNenSMMmVChjXWJFdmk="
      appid: "2017110709779731"
      gatewayUrl: "https://openapi.alipay.com/gateway.do"
      notify-url: ${server.service-domain}/alipay/notify